### ISSUE TITLE
Can ndarray be used directly or conveniently with plotly?

### ISSUE THREAD

**Issue by liufuyang** [igiagkiozis/plotly#1]
Hi there, this repo looks great. 

One question: can [ndarray](https://crates.io/crates/ndarray) be used directly or conveniently with plotly?

**Comment by igiagkiozis** [comment]
Hi @liufuyang,

At the moment it can only be used directly with Rust native types, but I agree support for displaying pairs of 1d-tensors and 2d-tensors for surface plots would be quite useful. Do you have a view on how the API could look like?

**Comment by igiagkiozis** [comment]
> Hi there, this repo looks great.
> 
> One question: can [ndarray](https://crates.io/crates/ndarray) be used directly or conveniently with plotly?

Hi @liufuyang,

At the moment it can only be used directly with Rust native types, but I agree support for displaying pairs of 1d-tensors and 2d-tensors for surface plots would be quite useful. Do you have a view on how the API could look like?

**Comment by liufuyang** [comment]
@igiagkiozis Hi there, thanks for the reply, for now I don't have much of an opinion on the API yet. As I only used the numpy and matplot lib a few times before, I feel, it would be great, if we could also make the connection between a Rust plot lib and a Rust version of numpy (which is ndarray I suppose) as smooth as possible :)

Would really like to help on this however I don't have the time and energy for it, maybe in the near future?

**Comment by igiagkiozis** [comment]
@liufuyang sounds good! Chances are I'll implement a feature to support a linear algebra crate soon-ish as I personally have need for it, but it's good to hear other people's views as inevitably my implementation will be tailored for my needs (mostly visualising Monte Carlo paths).

**Comment by igiagkiozis** [comment]
@liufuyang support for ndarray is available as of 0.6.0

**Comment by liufuyang** [comment]
Aha, very good to know, thank you for the info, will definitely try it out :)
