### ISSUE TITLE
Add pie and horizontal bar charts

### ISSUE THREAD

**Issue by jasonjurotich** [igiagkiozis/plotly#105]
I saw a similar issue to this opened before, so I thought it would be OK to add it here. Do you have plans on adding the pie and horizontal bar chart options from plotly in the near future? I could not find any examples anywhere for these two types, so I had to presuppose they were not implemented yet. Thanks.

**Comment by jasonjurotich** [comment]
I am guessing that maybe the orientation option would allow horizontal bar charts? https://docs.rs/plotly/latest/plotly/traces/bar/struct.Bar.html#method.orientation 

I have yet to find the pie chart option. Sorry again if this is out of place here.

**Comment by mfreeborn** [comment]
Thanks for opening this issue, you are quite right to do so.

Horizontal bar charts are indeed created by specifying the `orientation` parameter as you have found.

Pie charts are not yet implemented but will be in the "near future" either by myself or anyone who fancies having a go themselves and submitting a pull request :)

________________________________

**Comment by mfreeborn** [comment]
Closing this as it is tracked in #104
