### ISSUE TITLE
Build error in latest build 0.8.2 in wasm environment

### ISSUE THREAD

**Issue by piaoger** [igiagkiozis/plotly#121]
Updated to latest version and found below error. Seems no impl of show_with_default_app for wasm.

```
[dependencies]
plotly = {version="0.8.2", features=["wasm"]}
```
```text
177 | pub struct Plot {
    | --------------- function or associated item `show_with_default_app` not found for this struct
...
270 |         Plot::show_with_default_app(temp_path);
    |               ^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `Plot`
```

**Comment by mfreeborn** [comment]
Ah, I was trying to rationalize the feature gating, but apparently not correctly. I'll make sure to catch this sort of thing in CI and get a release out today with a bugfix. Thanks for pointing it out quickly.
________________________________
From: Piaoger ***@***.***>
Sent: Friday, November 4, 2022 8:05:20 AM
To: igiagkiozis/plotly ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [igiagkiozis/plotly] Build error in latest build 0.8.2 in wasm environment (Issue #121)


Updated to latest version and found below error. Seems no impl of show_with_default_app for wasm.

[dependencies]
plotly = {version="0.8.2", features=["wasm"]}


177 | pub struct Plot {
    | --------------- function or associated item `show_with_default_app` not found for this struct
...
270 |         Plot::show_with_default_app(temp_path);
    |               ^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `Plot`
