### ISSUE TITLE
Bin size changes after making histogram overlaid

### ISSUE THREAD

**Issue by wdecoster** [igiagkiozis/plotly#125]
Hi,

Thanks for this amazing crate! I am looking for suggestions on how to specify/synchronize the bin size for two histograms. When I plot just two histogram traces I get this result:

<img width="833" alt="image" src="https://user-images.githubusercontent.com/11660522/200818788-e5d77f33-dfd0-4896-a278-a64807ecb605.png">

However, when I set the layout to `Layout::new().bar_mode(BarMode::Overlay)` I get:

<img width="849" alt="image" src="https://user-images.githubusercontent.com/11660522/200818852-40bab5cb-7b7a-42d1-96d6-bffa6caa1e41.png">

The orange trace now uses fewer and wider bins? How do I change it to use the same bins as in the first example?

Thanks,
Wouter

**Comment by mfreeborn** [comment]
Hi Wouter, sorry for the delayed reply. This question would be better directed to a specific `plotly` help forum, as this library is just a thin wrapper over the canonical `plotly.js`.
