### ISSUE TITLE
Subplot support

### ISSUE THREAD

**Issue by nwoodbury** [igiagkiozis/plotly#13]
Would it be possible to get subplot support? 
At a minimum, it looks like methods would be needed to label and xaxis and a yaxis for traces such as Scatter, as well as the ability to define multiple axes in the layout, each with an anchor (see the examples at [https://plotly.com/javascript/subplots/](https://plotly.com/javascript/subplots/)). It would also be nice to have an API similar to the python library (see [https://plotly.com/python/subplots/](https://plotly.com/python/subplots/)).

**Comment by igiagkiozis** [comment]
@nwoodbury, yes I have that in my TODO list which got neglected lately; in most likelihood this feature will be in the next release in about 2-3 weeks.

**Comment by igiagkiozis** [comment]
@nwoodbury subplots and multiple-axis plots are supported since version 0.5.0.
