### ISSUE TITLE
Compiling for iOS or Unsupported Platforms

### ISSUE THREAD

**Issue by mjpauly** [igiagkiozis/plotly#134]
Hey all, thanks for the awesome crate. This is a small feature request that I'd like to discuss.

I'm compiling for iOS. Being able to call `plot.show();` is not important since I intend to generate the html and view that in a separate step. If I try to compile the library for iOS, I get the following error:

```
error[E0599]: no function or associated item named `show_with_default_app` found for struct `Plot` in the current scope
   --> external/crate_index_rustlib__plotly-0.8.3/src/plot.rs:271:15
    |
177 | pub struct Plot {
    | --------------- function or associated item `show_with_default_app` not found for this struct
...
271 |         Plot::show_with_default_app(temp_path);
    |               ^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `Plot`
```

My current workaround is to add an additional copy of this function back under a `#[cfg(target_os = "ios")]` attribute [like so](https://github.com/mjpauly/plotly/commit/eefd9bad221da4d44319d93b65d9f31e4286e420).

The attribute could be tweaked to be a catchall for any `target_os` where showing the plot with the default app is irrelevant or just not implemented yet.

**Comment by mfreeborn** [comment]
I would accept a PR which had a blanket implementation for unsupported OSes as you describe, thanks for raising this issue.

**Comment by mjpauly** [comment]
I've switched to a wasm environment, which resolves this issue for me. Feel free to reopen if anyone feels like this is an issue that still deserves fixing.
