### ISSUE TITLE
Axis Aspect Question

### ISSUE THREAD

**Issue by danielwolbach** [igiagkiozis/plotly#135]
How can I achive that all axis have the same aspect / the same range (in a scatter 3D plot)?

![grafik](https://user-images.githubusercontent.com/77749247/217138802-c2f96e32-d21b-437a-b05c-09adf5143272.png)

As you can see, the z-axis only goes to 40M while the x- and y-axis go to 150B. I would like them to have the same range.

**Comment by mfreeborn** [comment]
As this crate is just a wrapper around plotly.js, you're best bet is to seek help from them/user forums. If you have any trouble translating the syntax into the rust bindings, then please re-open this issue.
