### ISSUE TITLE
how to auto scale y axis when range slider moves

### ISSUE THREAD

**Issue by heestree** [igiagkiozis/plotly#136]
Hi, I am new to Plotly_rs and looking a way to auto scale y axis when range slider moves as shown in the following link. Please note that y axis is auto scaled during animation.

https://global.discourse-cdn.com/business7/uploads/plot/original/2X/5/5addc29efc2fbcbaf0db19beafd09bbacdf3c0e6.gif

**Comment by mfreeborn** [comment]
Could you include a minimal example of the code that you have tried that isn't working correctly? As this crate is just a thin wrapper around plotly.js, I suggest you seek help from plotly.js documentation/plotly forums etc directly. If you have any issues translating a javascript of python implementation into rust, then please reopen this issue with the code you are having trouble with.
