### ISSUE TITLE
Any plan to implement plotly.extendTraces() ?

### ISSUE THREAD

**Issue by samueldotj** [igiagkiozis/plotly#140]
plotly.js has a API to extend trace points which allows dynamically updating the charts possible.
https://plotly.com/javascript/plotlyjs-function-reference/#plotlyextendtraces

From the API documentation, I don't see a function which can used for this in this crate.
Please let me know if I missed an API which I missed.
If it is not yet implemented, is there any near future plans for it?

**Comment by mfreeborn** [comment]
There's no reason why it hasn't yet been implemented, other than the time involved in doing so. It's not currently very high on my personal to-do list, though.
