### ISSUE TITLE
LaTeX y-axis tick labels introduce additional spacing

### ISSUE THREAD

**Issue by Autoparallel** [igiagkiozis/plotly#146]
# The Problem
I am working with the following settings for my y-axis:

```rust
let y_axis = Axis::new()
        .title(Title::new(&y_label).font(Font::new().size(48)))
        .show_grid(true)
        .grid_color(PRIMITIVE_GREYS[MAIN_COLOR_SLOT])
        .zero_line(false)
        .show_line(true)
        .tick_prefix("$\\LARGE{")
        .tick_suffix("}$")
        .tick_font(Font::new().size(24))
        .auto_margin(false)
        .range(axes.bounds.1)
        .ticks(plotly::layout::TicksDirection::Outside);
```

The issue here is that with the chosen `.tick_prefix`, the y-axis tick labels (except for the first) have additional spacing that makes the labels collide with the y-axis title. My workaround has been to increase the font size of the y-axis title which does not change the visible font size when you are rendering TeX.

Here is an example output image:
![newplot-22](https://user-images.githubusercontent.com/20118821/234923730-e9f98aca-771f-4e44-99e6-d60884a633fa.png)

By increasing the size to 55, the collision can be avoided:
![newplot-23](https://user-images.githubusercontent.com/20118821/234924301-2fc253b4-de07-43b4-80ff-51c53d571984.png)

The real bug here seems to 
![SCR-20230427-e74](https://user-images.githubusercontent.com/20118821/234925111-317fa0f0-b855-4967-bab5-6b1285f91607.png)
be the additional whitespace to the right of the y-axis tick labels:

By removing the `tick_prefix` and `tick_suffix` and putting:
```rust
let y_axis = Axis::new()
        .title(Title::new(&y_label).font(Font::new().size(48)))
        .show_grid(true)
        .grid_color(PRIMITIVE_GREYS[MAIN_COLOR_SLOT])
        .zero_line(false)
        .show_line(true)
        .tick_prefix("")
        .tick_suffix("")
        .tick_font(Font::new().size(24))
        .auto_margin(false)
        .range(axes.bounds.1)
        .ticks(plotly::layout::TicksDirection::Outside);
```
we get the following:
![newplot-25](https://user-images.githubusercontent.com/20118821/234925782-55099ca5-32d3-4787-861b-840c35fd46f6.png)

## To reproduce the problem

Use the `y_axis` settings above. Of course, ignore the choice of immaterial settings. E.g., just use:
```rust
let y_axis = Axis::new()
        .title(Title::new(&y_label).font(Font::new().size(48)))
        .show_line(true)
        .tick_prefix("$\\LARGE{")
        .tick_suffix("}$")
        .tick_font(Font::new().size(24))
        .auto_margin(false)
        .range(vec![0.0,4000.0])
        .ticks(plotly::layout::TicksDirection::Outside);
```

For more precise implementation details, visit the repo where this work is occuring: [visualization-rs](https://github.com/primitivefinance/visualization-rs).

**Comment by mfreeborn** [comment]
This looks like an issue to be raised with the underlying `Plotly.js` library, for which this library is just a thin wrapper, but do correct me and reopen if there is an issue in the rust-specific issue.
