### ISSUE TITLE
Incorrect usage of x_axis, y_axis and z_axis in 3d plot layout

### ISSUE THREAD

**Issue by tectin0** [igiagkiozis/plotly#149]
Hello plotly-rs maintainers,

I tried to create a 3d scatter plot using the library in Rust version 0.8.3. I faced difficulty in customizing the axes labels for the plot and was consulting the example function customized_scatter3d_plot() available in the official repository.

After going through the code of the layout setup in the example function, I found that x_axis, y_axis, and z_axis were used to set the axis labels for a 3d plot. However, I figured out that these functions do not set the axis labels for a 3d plot. Instead, the Scene element has to be implemented to set the axis labels and other 3d properties.

The output of the function results in the following plot without any axis titles:

![newplot](https://github.com/igiagkiozis/plotly/assets/94180412/62bb2278-50f4-4c2e-96f9-7c0ba379e9ff)

I noticed that there was a pull request submitted a while ago which aimed to implement the Scene element for this functionality, but it was rejected for wrong formalities. I am interested in contributing to the project and wanted to know if a new pull request for implementing the Scene element would be welcomed.

Thank you!

**Comment by mfreeborn** [comment]
I would certainly be happy to review a PR as you describe.

**Comment by tectin0** [comment]
Ok, great, then I'll see if I can finish and test what I've coded so far.
