### ISSUE TITLE
Shapes Support

### ISSUE THREAD

**Issue by Number7tSeven** [igiagkiozis/plotly#17]
Id like to see this crate support shapes in Plotly (https://plotly.com/javascript/shapes/).

Due to a failure to read the contributing file on my part I already made an implementation. My bad. I'll wait for discussion before making a PR.

**Comment by igiagkiozis** [comment]
Hi @Number7tSeven, 

I had plans implementing this one but needed the multiple-axes support and associated subplots so that took priority. You're welcome to try your hand at implementing them.

**Comment by Number7tSeven** [comment]
It looks like you have already implemented this. Thanks for your time and effort on this project.

**Comment by igiagkiozis** [comment]
@Number7tSeven yes I have a initial implementation on the `dev` branch; so it'll be in the next release.

**Comment by igiagkiozis** [comment]
@Number7tSeven version 0.6.0 will be released today; you can have a look at the documentation [here](https://igiagkiozis.github.io/plotly/content/fundamentals/shapes.html)
