### ISSUE TITLE
Remove uneeded dependencies

### ISSUE THREAD

**Issue by etemesi-ke** [igiagkiozis/plotly#18]
version:`0.5.0`
(I know am early sorry)  
Dependencies like csv and itertools are only needed for examples and hence not needed for functioning of the crate
This could reduce the overall size footprint of the crate since its calling dependencies not needed

**Comment by igiagkiozis** [comment]
@etemesi-ke that's a good point.

**Comment by igiagkiozis** [comment]
@etemesi-ke removed in 0.5.1.
