### ISSUE TITLE
Display hundereds of plots

### ISSUE THREAD

**Issue by mindv0rtex** [igiagkiozis/plotly#21]
Yesterday I tried to write around 700 plots to an HTML file via calling `to_inline_html()` this many times into a vector of strings and then writing them all to an HTML template that only includes `plotly.js` once. My browser couldn't handle the resulting file very well. It is very slow. Are there any known tricks to make plotly behave more snappy in such situations? Or is this a complete misuse of the library on my part?

**Comment by igiagkiozis** [comment]
@mindv0rtex do you mind sharing an example I can experiment with?

**Comment by mindv0rtex** [comment]
I trimmed this file to 300 plots. You can already experience the slow-down. It eventually goes away when the loading is over. I admit I can't figure out what is being loaded...
https://www.dropbox.com/s/dm0j56ol0qvi6cn/diff.html?dl=0

**Comment by igiagkiozis** [comment]
The `Plot::to_inline_html` method generates a div block with the script for the corresponding plot. When the page is loaded, these script blocks are executed in sequence. Every execution delegates the plotting work to plotly.js, which means that if you have N of these plots in a page you'll incur N calls to plotly.js, specifically the `Plotly.newPlot` function. That function then generates the plot and injects in in the `div` with the corresponding `id`. As far as I'm aware javascript in the browser is single threaded and can execute functions at most concurrently, not in parallel. If parallel execution was available somehow, that could be leveraged to speed up the above process.

Short of parallel execution, which as far as I know is not possible, I would suggest that your best bet is splitting these plots in multiple pages. How many plots you can have on a single page would require some testing on your side; i.e. what kind delay is acceptable by your end user.

**Comment by mindv0rtex** [comment]
This makes sense! And makes me wonder whether there is some sort of mechanism to pre-render these charts to avoid the sequential `Plotly.newPlot` calls altogether.
