### ISSUE TITLE
Annotate things with #[must_use]

### ISSUE THREAD

**Issue by CGMossa** [igiagkiozis/plotly#22]
I love this project and would love to contribute anything at all.
I've been hearing a lot about `#[must_use]`, see [this](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute).

I'm thinking specifically about `Layout`. That thing needs to be used through a `some_plot.set_layout`.

What do you think? Should I try to give it a go?

**Comment by igiagkiozis** [comment]
Hi @CGMossa,

Can you give a short example to illustrate how you see this being used with layout?

**Comment by CGMossa** [comment]
Sorry I missed this.
I don't remember this at all.. But annotating things with `#[must_use]` is
very helpful.
