### ISSUE TITLE
Attempting to save in PNG format causes panic

### ISSUE THREAD

**Issue by jgoerzen** [igiagkiozis/plotly#23]
Hi,

I have this in Cargo.toml:

```
plotly = { version = "0.6", features = ["kaleido"] }
```

And, following the instructions, this in my code: `plot.save(filename, ImageFormat::PNG, 1024, 768, 1.0);`

The program crashes with this:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/jgoerzen/.cargo/registry/src/github.com-1ecc6299db9ec823/plotly_kaleido-0.2.0/src/lib.rs:97:13
```

That backtrace wasn't much help, but strace was:

```
21466 lstat("/home", {st_mode=S_IFDIR|0755, st_size=10, ...}) = 0
21466 lstat("/home/jgoerzen", {st_mode=S_IFDIR|0755, st_size=722, ...}) = 0
21466 lstat("/home/jgoerzen/tree", {st_mode=S_IFDIR|0755, st_size=248, ...}) = 0
21466 lstat("/home/jgoerzen/tree/plotly_kaleido", 0x7ffd64e387b0) = -1 ENOENT (No such file or directory)
```

The current working directory was a different one under /home/jgoerzen/tree.  

Why it expects ../plotly_kaleido to exist, I don't know.  What's supposed to be there, I also don't know.  The plotly documentation said there was some additional configuration necessary for plotly_kaleido but the plotly_kaleido documentation doesn't say what it is.  I couldn't find any documentation for how to set up plotly_kaleido or why it would be looking for something in `..`.  

Thanks for your work on this!

**Comment by jgoerzen** [comment]
It appears that if I:

1. mkdir ../plotly_kaleido
2. Download the linux kaleido zip file from the plotly kaleido project
3. Unzip the file in ../plotly_kaleido

that things work, because it expects to find something in ../plotly_kaleido/kaleido.  This is rather strange behavior (to expect to find something relative to a working directory) but should at least be documented and controllable.  Thanks!

**Comment by igiagkiozis** [comment]
@jgoerzen the build script downloads plotly kaleido and places it in that folder. What platform are you running on?

**Comment by Seriyin** [comment]
Facing the exact same problem. The build script may not be working as intended.

I'm running it under an up-to-date Pop!_OS 20.0.4 LTS 64-bit. Not very different from a lowest common denominator Ubuntu/Debian build.

My Cargo.toml, aside from typical package preamble only contains the following:

```TOML [dependencies]
plotly = { version = "0.6", features = ["kaleido"] }
plotly_kaleido = "0.2.0"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
glob = "0.3"
chrono = "0.4"```

Hope it helps in tracking down the weird behaviour! Keep up the great work. Plotly is insanely valueable.

**Comment by selvavm** [comment]
I am also facing the same issue and I reported it in #39. @jgoerzen method worked for me. I think build script is not working as intended.

**Comment by matthiascy** [comment]
I encountered the same problem when running it under latest Manjaro 64bit. It seems that this is still not fixed.

**Comment by matthiascy** [comment]
The problem is caused by this line [https://github.com/igiagkiozis/plotly/blob/870dfc6edad1cfb372a247227ea5769c09003202/plotly_kaleido/src/lib.rs#L88](plotly_kaleido), here it tries to find the binary path of the kaleido executable which is downloaded by the build script. The path is indicated by **CARGO_MANIFEST_DIR**. This is fine when you are developing the library, but if you use it in an anothor project, the binary is not downloaded directly in your project directory but in `~/.cargo/registry/github.com-xxxxxxxxxx/plotly_kaleido-0.2.0`, meanwhile **CARGO_MANIFEST_DIR** is your current project folder not the one where cargo stores the repo. That's why it cannot find the right executable to write the image.

**Comment by igiagkiozis** [comment]
That's a good point; I'll fix this in the upcoming release.

**Comment by igiagkiozis** [comment]
I've pushed a new version on dev that should address this issue. However, for the next couple of months I'll have access only to mac so if anyone could test this on Linux and Windows it'd be much appreciated.

**Comment by pauleaster** [comment]
Using 
`plotly = {git = "https://github.com/igiagkiozis/plotly", branch = "dev", features = ["kaleido"] } `
fixed the problems for me. For some reason the first build failed though but when I built it a second time it worked and successfully save the image to disk.
However, I was also using MacOS.
