### ISSUE TITLE
Need more options for saving without opening

### ISSUE THREAD

**Issue by jgoerzen** [igiagkiozis/plotly#24]
Hi,

The methods of Plot all talk about opening in the browser in the doc comments.  Fortunately, for to_html(), that is incorrect.  I want to generate plots in batch and script the process of posting them places.

However, I'll note that to_html() contains expect, which will cause a panic if a filename is bad or something.  It ought to return a Result so that proper error handling can occur.

**Comment by igiagkiozis** [comment]
@jgoerzen you can use the `plotly_kaleido` feature which enables the functionality you ask for; for an example see the last few lines of the [getting started guide](https://igiagkiozis.github.io/plotly/content/getting_started.html).

**Comment by jgoerzen** [comment]
Hi @igiagkiozis and thanks for your work on plotly!  I was unable to get kaleido to work.  But what I'm asking for shouldn't require that.  I did wind up getting it working; since, as I noted, for to_html() the docstring is actually incorrect and it doesn't open in the browser.
