### ISSUE TITLE
WASM Target compiliation

### ISSUE THREAD

**Issue by ykafia** [igiagkiozis/plotly#25]
I'm using seed-rs to display plots with the inline html.
seed-rs uses wasmpack which compile libraries with the wasm32-unknown-unknown target.

[Repo to reproduce the error](https://github.com/ykafia/MySeed)

```pwsh
error[E0599]: no function or associated item named `show_with_default_app` found for struct `plot::Plot` in the current scope
   --> C:\[...]\.cargo\git\checkouts\plotly-32f25712b3766afa\870dfc6\plotly\src\plot.rs:209:15
    |
96  | pub struct Plot {
    | --------------- function or associated item `show_with_default_app` not found for this
...
209 |         Plot::show_with_default_app(temp_path);
    |               ^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `plot::Plot`
```

**Comment by igiagkiozis** [comment]
@ykafia the function `show_with_default_app` is implemented only for `linux`, `windows` and `macos` which is why you're receiving this error. I haven't considered WASM integration yet however I'll be adding a few fixes that will help in that direction (see #26 )

**Comment by karakaplanm** [comment]
> @ykafia the function `show_with_default_app` is implemented only for `linux`, `windows` and `macos` which is why you're receiving this error. I haven't considered WASM integration yet however I'll be adding a few fixes that will help in that direction (see #26 )

Any progress on wasm integration?

**Comment by ykafia** [comment]
There's a branch/fork somewhere that has removed some stuff that binds the library to desktop

**Comment by igiagkiozis** [comment]
@ykafia I'll try and add this in the next release; however given that I'm quite busy with work right now any help would be appreciated.
