### ISSUE TITLE
Separate pure and system-specific (image file export, etc) code to enable the import into wasm-bindgen projects) 

### ISSUE THREAD

**Issue by antislava** [igiagkiozis/plotly#26]
System dependencies hinder using this crate in `wasm-bindgen` projects. What would be the optimal way to separate all the system-related code (templating and exporting image files) from the core "pure" code?
I tried a quick fix by introducing the "system" flag (should probably be named "export"...) and moving `Trace` trait and adding a smaller `PlotData` struct identical to `Plot` but keeping only `to_json` serialization method, to the new `pure` module (here `Plot` is a superset/overlaps with `PlotData` but can be trivially refactored by e.g. making `PlotData` a member of the `Plot` struct: https://github.com/igiagkiozis/plotly/compare/master...antislava:antislava-pure).
The export features are included under the "system" flag (that should probably be enabled by default).

This fix seems to work fine for me now but not sure if this is the best approach here (I'am new to Rust)

**Comment by igiagkiozis** [comment]
@antislava I don't see any obvious issues with that approach; I'll do a few experiments of my own and come back to you.
