### ISSUE TITLE
avoid multiple allocation for X cordinates

### ISSUE THREAD

**Issue by 20iahazban** [igiagkiozis/plotly#27]
Hi,

first of all sorry for the noob question!

In my rust code I would like to avoid multiple allocation for X cordinates. (because every trace need one)
In every example wich i have seen a new vector was allocated for X, for example:
![image](https://user-images.githubusercontent.com/30409619/91829195-7056fd80-ec41-11ea-99cc-24b84c7a642d.png)

how can I make a single vector for my X coordinates and use it for every trace? is it possible?

**Comment by ykrist** [comment]
You can use iterators:
```rust
let x_vals = vec![1, 2, 3, 4]
Scatter::new(x_vals.iter().copied(), vec![12, 9, 15, 12])
Scatter::new(x_vals.iter().copied(), vec![16, 11, 6, 10])
```
Unless you're creating thousands of traces, I don't think it'll make a noticeable difference.

**Comment by 20iahazban** [comment]
From .copied() i assume allocation is still happening
