### ISSUE TITLE
Margin right

### ISSUE THREAD

**Issue by shahinrostami** [igiagkiozis/plotly#3]
https://github.com/igiagkiozis/plotly/blob/71111ae26a506f734626a16d2e9b9cded1c43e9b/src/charts/mod.rs#L1987

With the above we are able to adjust the left, top, and bottom largins. Can we add the right margin too? If you're happy to accept pull requests, I could take a look in future

**Comment by igiagkiozis** [comment]
Hi @shahinrostami, 
I've already resolved this in version 0.4.0. (see https://github.com/igiagkiozis/plotly/blob/master/plotly/src/layout.rs)  Thanks for the offer though; if you find anything missing or you'd like to add I'm happy to consider a pull request.
