### ISSUE TITLE
Deprecate `panic!`s for `Result<T, E>`

### ISSUE THREAD

**Issue by Scipi** [igiagkiozis/plotly#33]
The widespread use of `.unwrap()` and `.expect()` make this library unsuitable for use in applications that need to be fault-tolerant, such as webservers, etc. Consider refactoring code that can fail to use an Error type that encapsulates what went wrong so client code can decide how to handle the failure. If you'd like, I can make this change and submit a pull-request.

**Comment by mfreeborn** [comment]
Closing this as it is tracked in #104
