### ISSUE TITLE
Plotly.js 2.0 compatibility

### ISSUE THREAD

**Issue by nicolaskruchten** [igiagkiozis/plotly#37]
Hi there,

I lead the graphing libraries team at Plotly where we're busy working on version 2.0 of Plotly.js. I'm reaching out to folks who we know are "downstream" of Plotly.js to give you a heads-up about the changes so you can let me know if/how disruptive they're likely to be for you :)

Our approach here is not to make gratuitous breaking changes, but mostly to drop support for un/under-used functionality that slows down development for frequently-used functionality. We expect that the vast majority of users of Plotly.js and downstream systems like Plotly.py, Plotly.R, PlotlyJS.jl, Plotly.NET etc will be unaffected by these changes. The tracking issue we've got going is here https://github.com/plotly/plotly.js/issues/5395

The major changes include, at the Javascript layer:
* dropping IE 9/10 support due to a switch in the `Promise` polyfill we're using, for security reasons
* dropping exports of old versions of `d3` modules under `Plotly.d3` (so we can upgrade them internally)
* dropping some exports of deprecated methods like `Plotly.plot` in favour of `Plotly.newPlot` and `Plotly.react`

The major changes at the schema layer:
* dropping support for `pointcloud`, `area` and `contourgl` traces, as well as the legacy polar attributes from `scatter` like `scatter.r` and `layout.angularaxis`
* dropping the `role` key from the schema altogether

I'm happy to answer any questions or consider changing our plans if it can avoid some major downstream disruption, so please get in touch or reply to this issue or to  https://github.com/plotly/plotly.js/issues/5395 :)

Nicolas

**Comment by igiagkiozis** [comment]
Hi Nicolas,

Thank you for the heads up; it is much appreciated! I've been preoccupied with other projects for a while but now I'm planning the upgrade. Will reach out to you if I come across any unexpected issues.

**Comment by nicolaskruchten** [comment]
Sounds great! We're up to 2.2.0 now and 2.3.0 is coming soon :)

**Comment by igiagkiozis** [comment]
I noticed :)
