### ISSUE TITLE
How to use plotly_kaleido?

### ISSUE THREAD

**Issue by selvavm** [igiagkiozis/plotly#39]
I have downloaded the kaleido as exe from their github and kept the executable in `C:\Users\selva\Downloads\kaleido_win_x64`. I have added it to the path temporarily using `setx path "%path%;C:\Users\selva\Downloads\kaleido_win_x64"`. 

Now if I run using below command, I am getting `could not find kaleido executable in path`

```
cargo test --package tester --test plot -- test_plotter --exact --nocapture
```

**Comment by matthiascy** [comment]
https://github.com/igiagkiozis/plotly/issues/23#issuecomment-879946595
