### ISSUE TITLE
Layout Template

### ISSUE THREAD

**Issue by shahinrostami** [igiagkiozis/plotly#4]
I have tried changing the template to something like "plotly_dark" but nothing changes - is the template for something else?

**Comment by igiagkiozis** [comment]
As I understand it the template is an entire JSON object containing defaults. So you'll need to serialise all the defaults in the correct format. I have plans to refine this part, but my plan is to smooth out the use of things that are most often used first. That said, help is always welcome ;)

**Comment by shahinrostami** [comment]
Ah I see. I was trying to find the equivalent functionality to the Plotly in Python, e.g. `fig.layout.template = 'theme_here'`

**Comment by igiagkiozis** [comment]
@shahinrostami you can get inline html in version `0.5.0` and above.
