### ISSUE TITLE
Axis ticks text has the wrong parameter name

### ISSUE THREAD

**Issue by cpg314** [igiagkiozis/plotly#45]
Thank you for this cool library.

It appears that the function https://docs.rs/plotly/0.6.0/plotly/layout/struct.Axis.html#method.tick_text to set ticks texts and values manually does not work. 

The reason for that seems to be that the `tick_text` parameter https://github.com/igiagkiozis/plotly/blob/870dfc6edad1cfb372a247227ea5769c09003202/plotly/src/layout.rs#L741 should be `ticktext` instead, following for example https://plotly.com/python/tick-formatting/:
```
fig.update_layout(
    xaxis = dict(
        tickmode = 'array',
        tickvals = [1, 3, 5, 7, 9, 11],
        ticktext = ['One', 'Three', 'Five', 'Seven', 'Nine', 'Eleven']
    )
)
```
Replacing the line above by ` #[serde(skip_serializing_if = "Option::is_none", rename = "ticktext")]` indeed does the trick.

**Comment by igiagkiozis** [comment]
Hi @cpg314,

Well spotted, I'm currently preparing a new release of the library, I'll include a fix in version 0.7.0. In the meantime I'll get this fixed in the dev branch this weekend.
