### ISSUE TITLE
various kinds of plots

### ISSUE THREAD

**Issue by JoelSjogren** [igiagkiozis/plotly#49]
it seems like plotly for rust doesn't support plotting these:

1. 3d mesh (https://plotly.com/python/3d-mesh/)
2. image loaded from disk/stored in array (https://plotly.com/python/imshow/)

am i right?

these features would be very nice to have.

**Comment by JoelSjogren** [comment]
(i am using evcxr in jupyterlab in linux)

**Comment by mfreeborn** [comment]
Happy to receive pull requests for new plot types. It's faitly straightforwards if you copy the style of other plot implementations. It's then mostly just a case of transcribing the plotly.js docs into Rust structs/enums.

**Comment by mfreeborn** [comment]
Closed by #88 - thanks very much on initiating this :)
