### ISSUE TITLE
Saving on windows is buggy 

### ISSUE THREAD

**Issue by CGMossa** [igiagkiozis/plotly#5]
I'm having some strange outputs from the `.to_pdf` and `.to_png` methods..

So in rust I am calling these 
```rust
        dam_density_plot.to_pdf("figures/dam_offspring_rate.pdf", 1600, 1000);
        dam_density_plot.to_png("figures/dam_offspring_rate.png", 1600, 1000);
```
and the results are strange.. (Before and after `.show()` does not change anything).

![dam_offspring_rate](https://user-images.githubusercontent.com/1063624/76612860-66b7cd00-651d-11ea-8aeb-7cf4ad25d228.png)

[dam_offspring_rate.pdf](https://github.com/igiagkiozis/plotly/files/4328975/dam_offspring_rate.pdf)

Maybe we need a unit converter to make these `usize`s make sense pixel wise or something?

**Comment by igiagkiozis** [comment]
Hi @CGMossa, 

I think this is an issue with Orca, have you tried reducing the width and height to see if that changes things. For example, try 1024x680, and see if that produces cleaner results. Whilst you do that I'll check on my end to see if anything is amiss.
