### ISSUE TITLE
Compilation failure for Kaleido feature (due to dependency)

### ISSUE THREAD

**Issue by joeftiger** [igiagkiozis/plotly#53]
Using plotly with
```toml
[dependencies]
plotly = { version = "0.7", features = ["kaleido"] }
```
leads to a compiler error:
```
Caused by:
  process didn't exit successfully: `/.../target/debug/build/plotly_kaleido-db1bf438fb17485d/build-script-build` (exit status: 101)
  --- stderr
      Updating crates.io index
    Installing ruget v0.4.3
     Compiling .... (omitted)
  error[E0432]: unresolved import `seahorse::color`
   --> /.../.cargo/registry/src/github.com-1ecc6299db9ec823/ruget-0.4.3/src/main.rs:6:16
    |
  6 | use seahorse::{color, Action, App, Flag, FlagType};
    |                ^^^^^ no `color` in the root

  For more information about this error, try `rustc --explain E0432`.
  error: failed to compile `ruget v0.4.3`, intermediate artifacts can be found at `/tmp/cargo-installdOI6h7`

  Caused by:
    could not compile `ruget` due to previous error
```

As far as I can see this stems from using `ruget` (in [plotly_kaleido/build.rs](https://github.com/igiagkiozis/plotly/blob/master/plotly_kaleido/build.rs#L104-L118)) to download some things.
The error stems from `ruget`'s dependency `seahorse::module` no longer being available.

`ruget` itself uses a version of `seahorse` however, where `seahorse::color` is still available.
I am a bit unsure why `cargo` seems to update `ruget`'s dependency when compiling it and how to fix it.

I have a brand new Linux install and have not changed any settings at all regarding rust/cargo.

**Comment by acshi** [comment]
The main issue is that seahorse made a breaking change removing the color module, but only updated the minor version number. This breaks cargo's assumption of semantic versioning.

You can get around this by installing ruget manually with the "--locked" option, and then the build script will use this version, since the build script runs it without this option.
`cargo install ruget --locked`

**Comment by acshi** [comment]
Seahorse has yanked the non-semantic versioning release and rereleased with a major version bump: https://github.com/ksk001100/seahorse/issues/70

So this issue should now be resolved.

**Comment by joeftiger** [comment]
Yes, I can confirm it works now :-)
Thank you for the update there!
