### ISSUE TITLE
offline mode

### ISSUE THREAD

**Issue by mrhrzg** [igiagkiozis/plotly#56]
There doesn't seem to be an offline mode for plotly.rs. While having a silly large html file that includes plotlyjs is not great for most use-cases, being able to look at plots when without web access can be great.
Is this a feature that would welcome?

**Comment by Ionizing** [comment]
Maybe you are looking for [`use_local_plotly`](https://docs.rs/plotly/latest/plotly/plot/struct.Plot.html#method.use_local_plotly) function?

**Comment by mrhrzg** [comment]
Yes! Thank you @Ionizing !

**Comment by mrhrzg** [comment]
Offline mode is already implemented and works. Great!
