### ISSUE TITLE
AWS Ubuntu - Fails to display image

### ISSUE THREAD

**Issue by ceikit** [igiagkiozis/plotly#6]
When running a Rust executable on a AWS Ubuntu Spot instance, the run fails with the following message:

`thread 'main' panicked at 'called Result::unwrap() on an Err value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/plotly-0.4.0/src/plot.rs:314:9
`
Otherwise runs fine in my local machine, opening the browser and displaying the image automatically

**Comment by igiagkiozis** [comment]
I think the instance may not have a web-browser or it hasn't assigned a default application for html files. Without this it's not possible for plotly to display the file. I'll add some error handling to detect this scenario, with suggestions as to the available alternatives in the error message.

**Comment by igiagkiozis** [comment]
Fixed in release 0.4.1
