### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by CGMossa** [igiagkiozis/plotly#7]
This is a great addition to the broader scientific computing ecosystem for Rust. 
I've not used plotly.js extensively, and I suspect a bunch of folks would want to try to use this crate without browsing the plotly-documentation.

So I thought I'd attempt to explore this repo and make some documentation here and there. This issue is to gather ideas, strategy, or whatever needs to be taken into account in order to improve the documentation of this crate.

For instance: Is there a dataset prelude that can be used to make examples with?

**Comment by igiagkiozis** [comment]
HI @CGMossa,

Although there are quite a few examples for this crate, I agree, documentation is lacking. I'm not sure I understand what you mean by "dataset prelude", could you elaborate?

**Comment by CGMossa** [comment]
I just found the `examples` folder, which is really what I thought wasn't there. It could be nice if those examples were spread around in the documentation, and reduced to showcase the important bits. I am going to try this a bit now, and see if it makes sense.

Yes! You could have one dataset(s) that you used to make complete plotly-examples.. I mean I am sure that's somewhere. But maybe this is too much to have lying around in this package.

**Comment by CGMossa** [comment]
I cannot figure out where to put a doc-string on say `x_calendar`, as it exists on `Bar`, `Box_plot`, etc.

**Comment by mfreeborn** [comment]
I'll close this issue for now as it is stale. Suffice to say, documentation remains an important part of ongoing development, and between the [book](https://igiagkiozis.github.io/plotly/content/getting_started.html), the [API docs](https://docs.rs/plotly/latest/plotly/) (of which I agree there is room for improvement) and the canonical [plotly.js docs](https://plotly.com/javascript/) it should be reasonably well covered.
