### ISSUE TITLE
Mapbox Support

### ISSUE THREAD

**Issue by AnBowell** [igiagkiozis/plotly#86]
Hi there, 

Love the crate and was wondering if there are any plans to add Mapbox support in future?

Many thanks,

Andrew

**Comment by mfreeborn** [comment]
Hi Andrew, thanks for your interest. Mapbox support is absolutely a feature that we wish to include in a future version - it's just a matter of defining the relevant structs which would serialize to the appropriate [json structure](https://plotly.com/javascript/reference/scattermapbox/).

**Comment by AnBowell** [comment]
That's great to hear! Thanks for getting onto this so quickly.
