### ISSUE TITLE
Request feature: Scatter3D

### ISSUE THREAD

**Issue by Banyc** [igiagkiozis/plotly#92]
I've noticed that the code has already been implemented and merged to `dev` branch https://github.com/igiagkiozis/plotly/pull/66. But in version `0.7.0`, there is still no `Scatter3D` available. Please merge `dev` to `master`, thanks!

**Comment by mfreeborn** [comment]
Indeed, the recent work is currently an sitting on the Dev branch at the moment. I've got some free time next week thati was planning on allocating to getting a new release out.
________________________________
From: IchHabeKeineNamen ***@***.***>
Sent: Friday, July 29, 2022 12:38:28 PM
To: igiagkiozis/plotly ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [igiagkiozis/plotly] Request feature: Scatter3D (Issue #92)


I've noticed that the code has already been implemented and merged to dev branch #66<https://github.com/igiagkiozis/plotly/pull/66>. But in version 0.7.0, there is still no Scatter3D available. Please merge dev to master, thanks!

**Comment by mfreeborn** [comment]
I've just initiated a discussion with the crate owner to see about cutting a 0.8.0 release. In my opinion, now is a good time to push out a new release before the next phase of work on the library.
